# pytorch cuda 基础镜像
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

ENV DEBIAN_FRONTEND noninteractive
ENV TZ="Asia/Shanghai"
USER root
WORKDIR /content

# utils
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y wget aria2 git git-lfs vim && rm -rf /var/lib/apt/lists/* && apt-get clean
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

EXPOSE 8080
CMD ["/bin/bash"]